"""Longer static sections extracted to keep report_builder.py <= 150 lines."""

from __future__ import annotations


def section_research_questions() -> str:
    return (
        "## 4. Research Questions\n\n"
        "**Q1: What was the bottleneck — RAM/VRAM or compute?**\n\n"
        "`facebook/opt-13b` requires ~26 GB FP16. This machine has 18 GB unified RAM, "
        "leaving ~7 GB free at runtime. The bottleneck is **RAM capacity** (memory wall), "
        "not compute. Identified analytically: model weight size > available RAM → direct load "
        "fails before a single forward pass executes.\n\n"
        "**Q2: How does AirLLM change resource allocation, and its relation to virtual memory/paging?**\n\n"
        "AirLLM implements transformer-layer-granularity demand paging: each layer shard is `mmap`'d, "
        "materialised into RAM for its forward pass, then released. Peak RAM = one layer (~45 MB) "
        "instead of the full 2.2 GB model. This mirrors OS virtual memory: pages in on fault, "
        "evict cold pages; AirLLM does the same at layer granularity. "
        "Cost: every token re-reads all 22 layers from NVMe.\n\n"
        "**Q3: Effect of quantization on memory, speed, quality? Where is the 'red line'?**\n\n"
        "FP16: 1108 MB peak RAM, 0.75 tok/s, quality 0.778. "
        "8bit/4bit: infeasible on macOS ARM — `bitsandbytes` requires CUDA. "
        "Theoretical: 8bit → ~554 MB / ~1.5 tok/s / minor quality loss; "
        "4bit → ~277 MB / ~3 tok/s / below instruction-following threshold. "
        "Red line is typically at 4bit.\n\n"
        "**Q4: How do Prefill and Decode manifest in TTFT vs TPOT?**\n\n"
        "TTFT = 27.96 s (median, 3 reps) — AirLLM streams all 22 layers from NVMe per call "
        "(prefill + decode combined in one MLX batched pass). "
        "TPOT = 0.0 s: MLX generates all tokens in one call; per-token ITL not measurable. "
        "Theoretically, TPOT ≈ one full 22-layer stream-read (~1.5 s/token) — "
        "heavily **disk-I/O-bound** rather than compute-bound.\n\n"
        "**Q5: Cost (Throughput/Latency) of running a large model on constrained hardware?**\n\n"
        "Throughput: 0.75 tok/s — ~200× slower than a GPU server. "
        "TTFT: ~28 s. Each NVMe read-modify-release cycle ≈ 1.54 s/layer × 22 layers = 33.8 s. "
        "Memory saved: 2.2 GB model → 1.1 GB peak RAM (50% reduction via AirLLM streaming). "
        "The constraint shifts from *memory* to *time*.\n\n"
        "**Q6: When is on-prem economically preferable, and when is API better?**\n\n"
        "Break-even: ~79.6 M tokens/month. Below this, managed API is cheaper (zero CapEx). "
        "Above it, on-prem amortises the $1,999 hardware cost ($65.53/month fixed). "
        "Non-cost factors for on-prem: data privacy, no internet dependency, no usage caps. "
        "Prompt caching (50% discount, 50% hit rate) shifts the break-even higher, "
        "favouring API for repetitive workloads."
    )


def section_run_instructions() -> str:
    return (
        "## 17. How to Reproduce\n\n"
        "```bash\n"
        "# 1. Clone and install\n"
        "git clone https://github.com/yosefshanaa/HW5.git\n"
        "cd HW5\n"
        "uv sync                   # creates .venv, installs all deps from uv.lock\n\n"
        "# 2. Configure secrets\n"
        "cp .env-example .env      # then fill HF_TOKEN if gated model needed\n\n"
        "# 3. Run all phases (internet required for first download)\n"
        "uv run baseline           # Phase 1: sanity + OOM proof (~1 s)\n"
        "uv run airllm-demo        # Phase 2: download TinyLlama + demo (~5 min)\n"
        "uv run sweep              # Phase 3: FP16/8bit/4bit sweep\n"
        "uv run benchmark          # Phase 4: >=3 reps, F1-F5 figures\n"
        "uv run economics          # Phase 5: break-even chart\n"
        "uv run ext-io             # Phase 6a: I/O sensitivity (F7)\n"
        "uv run ext-pagecache      # Phase 6b: page-cache warmup (F6)\n"
        "uv run report             # Phase 7: regenerate this README\n\n"
        "# 4. Run tests\n"
        "uv run pytest             # 131 tests, >=88% coverage, ~10 s\n"
        "```\n\n"
        "**Requirements:** Python 3.12, uv >=0.5, ~15 GB free disk, internet for download.\n\n"
        "**Troubleshooting:**\n\n"
        "| Symptom | Cause | Fix |\n|---|---|---|\n"
        "| `HF_TOKEN missing` | `.env` not created | `cp .env-example .env`, add token |\n"
        "| `bitsandbytes` error | CUDA-only dep; macOS incompatible | Expected; documented |\n"
        "| Long first run (>40 s) | Cold shard cache | Normal; re-run for warm cache |\n"
        "| OOM on baseline | System RAM pressure | Close browsers; re-run |"
    )
