"""Architecture, ADR, and engineering-quality section builders."""

from __future__ import annotations


def section_architecture() -> str:
    return (
        "## 13. Architecture & Code Design\n\n"
        "### 13.1 Four-Layer SDK Architecture\n\n"
        "```\n"
        "+-----------------------------------------------------------------+\n"
        "|  REPORT   README.md . results/*.csv|json . assets/*.png        |\n"
        "+-----------------------------------------------------------------+\n"
        "                              ^ figures, tables\n"
        "+-----------------------------------------------------------------+\n"
        "|  SERVICES  baseline_runner . airllm_runner . quant_sweep       |\n"
        "|            benchmark_pipeline . economic_model . report_builder |\n"
        "|            extension_e1_io . extension_e3_pagecache            |\n"
        "+-----------------------------------------------------------------+\n"
        "                              ^ calls\n"
        "+-----------------------------------------------------------------+\n"
        "|  SDK   model_loader (AirLLM/HF/Ollama)                         |\n"
        "|        metrics (TTFT/TPOT/RAM/energy) . quality . viz          |\n"
        "|        economics (onprem/api/breakeven)                        |\n"
        "+-----------------------------------------------------------------+\n"
        "                              ^ uses\n"
        "+-----------------------------------------------------------------+\n"
        "|  SHARED  gatekeeper . config . version . logging . preflight   |\n"
        "+-----------------------------------------------------------------+\n"
        "                              ^ runs on\n"
        "+-----------------------------------------------------------------+\n"
        "|  HARDWARE  Apple M3 Pro . 18 GB unified RAM . NVMe . no CUDA   |\n"
        "+-----------------------------------------------------------------+\n"
        "```\n\n"
        "### 13.2 Runtime Data-Flow (one benchmarked generation)\n\n"
        "```\n"
        "config + gatekeeper(env: HF_TOKEN)\n"
        "  |\n"
        "  v  preflight: python/torch/disk/tokenizer checks\n"
        "  |\n"
        "  v  Backend.load(model_id, precision, shards='~/airllm_cache')\n"
        "  |  AirLLM splits weights -> 22 layer shards x ~93 MB each on NVMe\n"
        "  |\n"
        "  v  cold/warm cache decision -> RAM sampler + wall clock start\n"
        "  |\n"
        "  v  generate(prompt, max_new_tokens=20)\n"
        "  |  for k in 0..21: mmap shard_k -> forward pass -> release shard_k\n"
        "  |  AirLLM MLX: all tokens in one batched call (TTFT = total latency)\n"
        "  |\n"
        "  v  record: TTFT . TPOT . tok/s . peak_RAM_MB . energy_J . output\n"
        "  |\n"
        "  v  quality_rater(output) -> quality_normalised in [0, 1]\n"
        "  |\n"
        "  v  results/*.csv|json -> viz.plots -> assets/*.png -> README.md\n"
        "```\n\n"
        "### 13.3 Backend Strategy (Device-Agnostic)\n\n"
        "| Backend | Role | Device |\n|---|---|---|\n"
        "| `AirLLMBackend` | Layer-streaming via `mmap`; shards on NVMe | CPU (MLX on Apple Silicon) |\n"
        "| `HFTransformersBackend` | Direct load; used for baseline OOM proof | CPU (expected to fail analytically) |\n"
        "| `OllamaBackend` | Small-model sanity baseline via local Ollama | CPU |\n\n"
        "Device resolved at runtime: `torch.cuda.is_available()` → `torch.backends.mps.is_available()` → CPU. "
        "Never hard-coded.\n\n"
        "### 13.4 API Gatekeeper (Security Chokepoint)\n\n"
        "No module reads `os.environ` directly except `shared/gatekeeper.py`:\n\n"
        "```python\n"
        "class Gatekeeper:\n"
        "    def hf_token(self) -> str | None:\n"
        "        return os.environ.get('HF_TOKEN')   # NEVER hard-coded\n"
        "    def require_hf_token(self) -> str:\n"
        "        tok = self.hf_token()\n"
        "        if not tok: raise ConfigError('HF_TOKEN missing -- see .env-example')\n"
        "        return tok\n"
        "```\n\n"
        "`.env` git-ignored; `.env-example` has placeholders; tokens never logged "
        "(`TokenRedactFilter` strips `hf_[A-Za-z0-9]{20,}`); `safetensors` only (no pickle).\n\n"
        "### 13.5 Architecture Decision Records (ADRs)\n\n"
        "| ADR | Decision | Consequence |\n|---|---|---|\n"
        "| **ADR-001** | CPU-only; device detected at runtime; no CUDA assumed | "
        "Most honest stress test of AirLLM's memory->time trade; bitsandbytes unavailable |\n"
        "| **ADR-002** | opt-13b = analytic OOM proof (no 26 GB download); TinyLlama = live demo | "
        "K1 met without wasting disk; LLaMA arch compatible with MLX backend |\n"
        "| **ADR-003** | Shards at `~/airllm_cache`; E1 benchmarks NVMe vs /tmp | "
        "System root not flooded; I/O sensitivity becomes a measured insight |\n"
        "| **ADR-004** | 8bit/4bit infeasible on macOS (bitsandbytes CUDA-only); documented | "
        "Honest negative result with theoretical projections; AC-9 satisfied |\n"
        "| **ADR-005** | Python 3.12 pinned via `uv python pin` | "
        "torch/airllm wheels exist; reproducible install |\n"
        "| **ADR-006** | `uv` only, no pip; `pyproject.toml` + `uv.lock` committed | "
        "Fully reproducible env from a clean clone |\n"
        "| **ADR-007** | `safetensors` over pickle; AirLLM `mmap` partial-load | "
        "No pickle RCE vector; aligns with AirLLM's design |\n"
        "| **ADR-008** | Raw results committed; all figures generated from data | "
        "Every chart auditable; AC-2 satisfied |"
    )


def section_quality_gates(coverage_pct: float = 88.0) -> str:
    return (
        "## 14. Engineering Quality Gates\n\n"
        "All gates must pass before any commit is accepted.\n\n"
        "### 14.1 Test Suite\n\n"
        f"**131 tests · {coverage_pct:.0f}% line coverage · ~10 s runtime**\n\n"
        "| Module group | # tests | Focus area |\n|---|---|---|\n"
        "| `test_gatekeeper`, `test_config` | 9 | Secrets from env only; config validation |\n"
        "| `test_economics`, `test_economic_model*` | 14 | CAPEX/OPEX, API pricing, break-even |\n"
        "| `test_timing`, `test_memory`, `test_energy` | 11 | TTFT/TPOT, RAM sampling, energy |\n"
        "| `test_quality_rater`, `test_benchmark_pipeline` | 9 | Rubric scoring, median/IQR |\n"
        "| `test_extensions` | 2 | E1 location runner, E3 page-cache runner |\n"
        "| `test_report_builder`, `test_viz_tables`, `test_plots` | 8 | README assembly, figures |\n"
        "| `test_preflight`, `test_quality_gate` | 8 | Env checks, gate logic |\n"
        "| AirLLM/HF/Ollama backends, runners, sweep | 70 | Backend adapters, pipeline |\n\n"
        "### 14.2 Ruff Linting — 0 violations\n\n"
        "```toml\n"
        "[tool.ruff.lint]\n"
        'select = ["E","F","W","I","N","UP","B","C4","SIM"]\n'
        "```\n\n"
        "Enforces: sorted imports, no unused symbols, no bare `except`, "
        "no deprecated syntax, no mutable defaults, no unnecessary comprehensions.\n\n"
        "### 14.3 Module Line-Count Gate (<=150 lines/file)\n\n"
        "Enforced by `shared/quality_gate.py`. Splits by concern when a file grows:\n\n"
        "| File | Lines | Responsibility |\n|---|---|---|\n"
        "| `report_builder.py` | ~148 | Assembles README from helper functions |\n"
        "| `_report_sections.py` | ~100 | Header, hardware, model, baseline, AirLLM sections |\n"
        "| `_report_theory.py` | ~150 | Theory, roofline, E1, E3, ISO sections |\n"
        "| `_report_content.py` | ~80 | Research Q&A and reproduction instructions |\n"
        "| `_report_architecture.py` | ~145 | C4 diagrams, ADRs, quality gates |\n"
        "| `_report_extras.py` | ~95 | KPI scorecard, prompt log, raw benchmark table |\n\n"
        "### 14.4 Security Gate\n\n"
        "- `.gitignore` covers `.env`, `.venv`, `airllm_cache/`, `__pycache__/`\n"
        "- No token in any committed file (`.env-example` has placeholders only)\n"
        "- `TokenRedactFilter` strips `hf_[A-Za-z0-9]{20,}` from all log output\n"
        "- `safetensors` shards exclusively — no `pickle` load path in any backend\n"
        "- Secret scan in `quality_gate.py` catches any accidental token commit\n\n"
        "### 14.5 Version Tracking\n\n"
        "```python\n"
        "# shared/version.py\n"
        '__version__ = "1.00"\n'
        "```\n\n"
        "Semantic versioning from 1.00. Every substantive change to results or "
        "interfaces increments the version and regenerates the README."
    )
