"""Project planning & documentation section builder."""

from __future__ import annotations


def section_planning_docs() -> str:
    """Return the full planning & documentation section for the README report."""
    return (
        "## Project Planning & Documentation\n\n"
        "This project was built **document-first**: PRD → PLAN → TODO → code. "
        "All planning documents live in [`docs/`](docs/) and are versioned alongside the source.\n\n"
        "| Document | Purpose | Highlights |\n|---|---|---|\n"
        "| [PRD.md](docs/PRD.md) | Master requirements | 6 goals · 23 FRs · 10 NFRs · 8 KPIs · 9 ACs · 9 risks |\n"
        "| [PLAN.md](docs/PLAN.md) | Architecture & decisions | C4 diagrams · data-flow · 8 ADRs |\n"
        "| [TODO.md](docs/TODO.md) | Phased execution backlog | 8 phases · 47 tasks · DoD per task |\n"
        "| [PRD_airllm.md](docs/PRD_airllm.md) | AirLLM mechanism deep-dive | 10 AFs · mmap/page-fault design |\n"
        "| [PRD_quantization.md](docs/PRD_quantization.md) | Precision sweep design | FP16/8bit/4bit matrix · CPU constraints |\n"
        "| [PRD_benchmarking.md](docs/PRD_benchmarking.md) | Metrics harness design | TTFT/TPOT/RAM/energy/quality spec |\n"
        "| [PRD_economic_analysis.md](docs/PRD_economic_analysis.md) | Economics model design | CAPEX/OPEX/API/break-even spec |\n"
        "| [prompt_engineering_log.md](docs/prompt_engineering_log.md) | AI-assisted dev log | Key prompts · decisions · outcomes |\n\n"
        "### PRD Highlights\n\n"
        "**Goals (G1–G6)**\n\n"
        "| ID | Goal |\n|---|---|\n"
        "| G1 | Prove a model that *cannot* load normally **can** run via AirLLM |\n"
        "| G2 | Quantify memory↔latency trade-off across ≥ 3 precision levels |\n"
        "| G3 | Produce a decision-grade economic model: On-Prem vs Managed API |\n"
        "| G4 | Tie every number to systems theory (Memory Wall, prefill/decode, mmap) |\n"
        "| G5 | Pass the engineering bar: uv · TDD ≥ 85% · Ruff 0 · ≤ 150 lines · gatekeeper |\n"
        "| G6 | Deliver ≥ 1 original extension beyond required tasks |\n\n"
        "**Key user stories:** researcher runs a 70B-class model on 8 GB RAM with no GPU (US-1); "
        "engineer gets a break-even chart to justify a hardware purchase (US-3); "
        "grader reproduces every figure with one command (US-4).\n\n"
        "**Acceptance criteria (all met ✓):**\n\n"
        "| AC | Criterion | Status |\n|---|---|---|\n"
        "| AC-1 | README is a complete technical report with all required sections & figures | ✓ |\n"
        "| AC-2 | Every figure regenerated from committed `results/` data | ✓ |\n"
        "| AC-3 | `uv sync` + run works from a clean clone | ✓ |\n"
        "| AC-4 | Ruff 0 violations · ≥ 85% coverage · no file > 150 lines | ✓ |\n"
        "| AC-5 | No secrets · `.env-example` present · gatekeeper used | ✓ |\n"
        "| AC-6 | `docs/` contains PRD · PLAN · TODO · 4 mechanism PRDs | ✓ |\n"
        "| AC-7 | Version 1.00 · prompt-engineering log · ISO/IEC 25010 mapping | ✓ |\n"
        "| AC-8 | ≥ 3 precision levels · ≥ 3 reps · break-even · ≥ 1 extension | ✓ |\n"
        "| AC-9 | Infeasible items (8bit/4bit on macOS ARM) documented with evidence | ✓ |\n\n"
        "### PLAN — Architecture Decision Records (ADRs)\n\n"
        "Eight decisions were formally recorded before implementation:\n\n"
        "| ADR | Decision | Why it matters |\n|---|---|---|\n"
        "| ADR-001 | CPU-only execution; device detected at runtime | M3 Pro has no CUDA; honest worst-case stress test |\n"
        "| ADR-002 | opt-13b = analytic OOM proof; TinyLlama = live demo | Avoids 26 GB download; LLaMA arch required for MLX |\n"
        "| ADR-003 | Shards at `~/airllm_cache`; E1 benchmarks NVMe vs /tmp | Keeps system root clean; I/O sensitivity becomes data |\n"
        "| ADR-004 | 8bit/4bit infeasible (bitsandbytes CUDA-only); documented | Honest negative result with theoretical projections |\n"
        "| ADR-005 | Python 3.12 pinned via `uv python pin` | torch/airllm wheels exist; reproducible lock |\n"
        "| ADR-006 | `uv` only, never pip; `pyproject.toml` + `uv.lock` committed | Fully reproducible from a clean clone |\n"
        "| ADR-007 | `safetensors` exclusively (no pickle) | No pickle RCE vector; aligns with AirLLM mmap design |\n"
        "| ADR-008 | Raw results committed; figures generated, never hand-drawn | Every chart is auditable and reproducible |\n\n"
        "### TODO — Phased Execution (P0 → P7)\n\n"
        "| Phase | Theme | Tasks | Outcome |\n|---|---|---|---|\n"
        "| **P0** | Repo · env · guardrails | 11 | uv env · gatekeeper · config · quality gate · CHANGELOG |\n"
        "| **P1** | Baseline — evidence of the problem | 4 | OOM proof (opt-13b 26 GB > 18 GB RAM) · Ollama sanity run |\n"
        "| **P2** | AirLLM integration (K1) | 6 | TinyLlama generates coherent output; K1 met |\n"
        "| **P3** | Quantization sweep (K2/K3) | 5 | FP16 complete; 8bit/4bit infeasible on macOS ARM; documented |\n"
        "| **P4** | Benchmark harness + figures (K4) | 7 | 3 reps · median+IQR · TTFT/TPOT/RAM/energy/quality · F1–F5 |\n"
        "| **P5** | Economic analysis (K5) | 4 | Break-even 79.6 M tok/mo · E_breakeven.png · assumptions table |\n"
        "| **P6** | Theory linkage + extensions (K6/K8) | 5 | §9 theory · E1 I/O · E3 page-cache · F6 · F7 |\n"
        "| **P7** | Report assembly + quality gate (K7) | 7 | README 615 lines · 18 sections · all gates green · v1.00 |\n\n"
        "> All 47 tasks completed. "
        "The full task list with per-task Definition of Done is in [docs/TODO.md](docs/TODO.md)."
    )
