"""Phase 7: Assemble all figures/tables into README.md report."""

from __future__ import annotations

import json
from pathlib import Path

from airllm_local_lab.sdk.viz.tables import hardware_table, precision_sweep_table
from airllm_local_lab.services._report_sections import (
    _HW,
    section_airllm,
    section_baseline,
    section_header,
    section_models,
    section_theory_iso,
)
from airllm_local_lab.shared.logging import get_logger
from airllm_local_lab.shared.version import __version__

log = get_logger(__name__)
ROOT = Path(__file__).resolve().parents[4]
RESULTS = ROOT / "results"
ASSETS = ROOT / "assets"


def _load_json(path: Path) -> dict | list | None:
    if path.exists():
        return json.loads(path.read_text())
    return None


def _fig(name: str, caption: str) -> str:
    p = ASSETS / name
    if p.exists():
        return f"![{caption}](assets/{name})\n*{caption}*\n"
    return f"*Figure not yet generated: {name}*\n"


def main() -> None:
    baseline = _load_json(RESULTS / "baseline.json") or {}
    demo = _load_json(RESULTS / "airllm_demo.json") or {}
    economics = _load_json(RESULTS / "economics.json") or {}
    summary_rows: list[dict] = _load_json(RESULTS / "benchmark_summary.json") or []  # type: ignore[assignment]
    ok_rows = [r for r in summary_rows if isinstance(r, dict) and r.get("status") == "ok"]

    hw_md = hardware_table(_HW)
    sweep_md = precision_sweep_table(ok_rows) if ok_rows else "*Sweep not yet run.*"
    assumptions_file = ASSETS / "economics_assumptions.md"
    assumptions_md = assumptions_file.read_text() if assumptions_file.exists() else "*Economics not yet run.*"

    crossover = economics.get("crossover_tokens")
    crossover_str = f"{crossover:,.0f}" if crossover else "N/A"

    fig_captions = [
        ("F1_memory_footprint.png", "F1 — Peak RAM and shard size vs precision"),
        ("F2_latency.png", "F2 — TTFT and TPOT vs precision"),
        ("F3_throughput.png", "F3 — Throughput vs precision"),
        ("F4_quality_vs_memory.png", "F4 — Quality vs memory trade-off"),
        ("F5_layer_timeline.png", "F5 — Per-layer load vs compute timeline"),
        ("F6_page_cache_warmup.png", "F6 — Cold → warm page-cache speedup"),
        ("F7_io_location.png", "F7 — Shard-location I/O sensitivity (Extension E1)"),
        ("E_breakeven.png", "Break-even: On-Prem vs Managed API vs Cloud GPU"),
    ]
    figs = {n: _fig(n, c) for n, c in fig_captions}

    sections = [
        section_header(__version__),
        f"## 1. Hardware\n\n{hw_md}\n\n**Critical constraint:** 18 GB unified RAM vs ~140 GB for a 70B FP16 model → AirLLM's layer-streaming is the only feasible path.",
        section_models(),
        section_baseline(baseline.get("sanity", {}), baseline.get("direct_load", {})),
        section_airllm(demo),
        f"## 5. Quantization Sweep\n\n{sweep_md}\n\n{figs['F1_memory_footprint.png']}{figs['F2_latency.png']}{figs['F3_throughput.png']}{figs['F4_quality_vs_memory.png']}",
        f"## 6. Benchmarking\n\n{figs['F5_layer_timeline.png']}{figs['F6_page_cache_warmup.png']}{figs['F7_io_location.png']}",
        f"## 7. Economic Analysis\n\n**Break-even:** ~{crossover_str} tokens/month\n\n{figs['E_breakeven.png']}\n\n### Assumptions\n{assumptions_md}",
        section_theory_iso(figs["F7_io_location.png"], figs["F6_page_cache_warmup.png"]),
        f"*Generated by `uv run report` · v{__version__} · 2026-06-17*",
    ]

    (ROOT / "README.md").write_text("\n\n---\n\n".join(sections))
    log.info("README.md report assembled (v%s)", __version__)
